# Generated by Django 5.0.4 on 2024-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('item_description', models.TextField(blank=True)),
                ('item_photo', models.ImageField(default=None, null=True, upload_to='photos/%Y/%m/%d')),
                ('item_price', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('availability_status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default=None, max_length=255, null=True)),
                ('item_category', models.CharField(blank=True, choices=[('Food', 'Food'), ('Drinks', 'Drinks'), ('Snacks', 'Snacks')], default=None, max_length=255, null=True)),
            ],
        ),
    ]
