# Generated by Django 5.0.4 on 2024-05-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_item', '0003_alter_menuitem_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_price',
            field=models.CharField(blank=True, default='2', max_length=255, null=True),
        ),
    ]
