# Generated by Django 5.0.4 on 2024-07-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_item', '0004_alter_menuitem_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
