# Generated by Django 5.0.4 on 2024-09-16 17:35

import menu_item.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_item', '0005_alter_menuitem_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_photo',
            field=models.ImageField(default=None, null=True, upload_to=menu_item.models.upload_to),
        ),
    ]
