# Generated by Django 5.0.4 on 2024-05-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('menu_item', '0002_initial'),
        ('order', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('total_price', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('item_price', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('item_quantity', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('total_price', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_item.menuitem')),
            ],
        ),
    ]
