# Generated by Django 5.1.1 on 2024-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderitem_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_category',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
