# Generated by Django 5.1.1 on 2024-09-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_orderitem_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_photo',
            field=models.ImageField(default=None, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
