# Generated by Django 5.1.1 on 2024-09-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_cartitem_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_category',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
